theme: jekyll-theme-minimal
logo: "figures/logo-j.png"
repository: visualinteractivedata/visualinteractivedata.github.io
github: [metadata]
relative_links:
  enabled: true
  collections: true
plugins: [jekyll-seo-tag]
collections:
  projects:
    output: true
    order:
      - education.md
      - clinical_guidelines.md.md
      - professional_course.md
      - cheat_sheets.md
      - data_comics.md
      - immmersive_analytics.md
      - networks.md
      - geospatial_networks.md
